services:
  # Web Service for API
  - type: web
    name: tax-law-api
    env: python
    buildCommand: sh -c "cd TAX_LAW_API && pip install -r requirements.txt"
    startCommand: sh -c "cd TAX_LAW_API && python services/tax_law_api.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: taxlawlegato

  # Background Worker for Ingestion
  - type: worker
    name: tax-law-ingest
    env: python
    buildCommand: sh -c "cd TAX_LAW_API && pip install -r requirements.txt"
    startCommand: sh -c "cd TAX_LAW_API && python services/ingest.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: taxlawlegato