services:
  # Web Service for API
  - type: web
    name: tax-law-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python services/tax_law_api.py  # This is correct
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: taxlawlegato

  # Background Worker for Ingestion
  - type: worker
    name: tax-law-ingest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./render_ingest_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: taxlawlegato 